AllCops:
  Include:
    - Berksfile
    - Gemfile
    - Rakefile
    - Thorfile
    - Guardfile
  Exclude:
    - vendor/**

ClassLength:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
HashSyntax:
  Enabled: false
LineLength:
  Enabled: false
MethodLength:
  Enabled: false
SignalException:
  Enabled: false
TrailingComma:
  Enabled: false
WordArray:
  Enabled: false

Style/SingleSpaceBeforeFirstArg:
  Enabled: false
Style/FileName:
  Enabled: false
Style/IndentHash:
  Enabled: false
Style/IndentArray:
  Enabled: false
Style/FirstParameterIndentation:
  Enabled: false
Style/ClosingParenthesisIndentation:
  Enabled: false
